apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: anarchy-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Anarchy Ansible Framework
  displayName: Anarchy
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ansible
  links:
  - name: Anarchy
    url: https://github.com/redhat-cop/anarchy
  maintainers:
  - email: jkupfere@redhat.com
    name: Johnathan Kupferer
  maturity: stable
  provider:
    name: Red Hat Communities of Practice
    url: https://github.com/redhat-cop/anarchy
  version: 0.0.0
