# permissions for end users to edit anarchycommunes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anarchy-commune-editor
rules:
- apiGroups:
  - anarchy.gpte.redhat.com
  resources:
  - anarchycommunes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anarchy.gpte.redhat.com
  resources:
  - anarchycommunes/status
  verbs:
  - get
